spring.application.name=game-session-service
server.port=8082

game-engine.base-url=http://localhost:8081
game-engine.connect-timeout=2s
game-engine.read-timeout=5s

session.simulation.move-delay=500ms
